# VARIABLES

BOX_IMAGE = "debian/bookworm64"
PROVIDER = "virtualbox"
NOM_MAQUINA_VIRTUAL = "pj9f4a7.1_helbca"
NUM_CPUS = 2
MEMORIA_RAM = 2048
PORT_FIS1 = 8000
PORT_FIS2 = 8080
PORT_VIR1 = 80
PORT_VIR2 = 9999
CARPETA_MAQ_FIS = "../codis"
CARPETA_MAQ_VIR = "/home/vagrant/codis"

# CONFIGURACIÓ DE LA MÀQUINA
Vagrant.configure("2") do |config|

  # BOX
  config.vm.box = BOX_IMAGE

  # CONFIGURACIÓ ESPECÍFICA DEL PROVIDER
  config.vm.provider PROVIDER do |provider|
    provider.name = NOM_MAQUINA_VIRTUAL
    provider.memory = MEMORIA_RAM
    provider.cpus = NUM_CPUS
    provider.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    provider.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end

  # CONFIGURACIÓ GENERAL
  config.vm.hostname = "pj9f4a7.1-helbca.fjeclot.net"
  config.vm.synced_folder CARPETA_MAQ_FIS, CARPETA_MAQ_VIR
  config.vm.network "forwarded_port", guest: PORT_VIR1, host: PORT_FIS1, protocol: "tcp"
  config.vm.network "forwarded_port", guest: PORT_VIR2, host: PORT_FIS2, protocol: "tcp"

  # PROGRAMARI A INSTAL·LAR I ORDRES A EXECUTAR DURANT LA CREACIÓ DE LA MÀQUINA
  config.vm.provision "shell", inline: <<-SHELL
    # Actualització de paquets
    sudo apt-get update
    sudo apt-get install -y aptitude net-tools whois

    # Instal·lació de Docker
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo usermod -aG docker vagrant
  SHELL

end
